---
services:
  Lubuntu:
    image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
    container_name: lubuntu
    environment:
      - USER=
      - PASSWORD=
      - VNC_PASSWORD=
      - RESOLUTION=1304x681 # optional
      - RELATIVE_URL_ROOT=/home
    volumes:
      - /dev/shm:/dev/shm
      - /path/to/config:/config
    ports:
      - 5900:5900
      - 6080:80
    restart: unless-stopped
